apiVersion: v1
kind: ReplicationController
metadata:
  name: powerjob-mysql
spec:
  replicas: 1
  selector: 
    app: powerjob-mysql 
  template:
    metadata:
      labels:
        app: powerjob-mysql 
    spec:
      containers:
      - name: powerjob-mysql
        image: powerjob/powerjob-mysql:latest   
        ports:
        - containerPort: 3306
        args: ["--lower_case_table_names=1"]
        env:
        - name: MYSQL_ROOT_HOST
          value: "%"
        - name: MYSQL_ROOT_PASSWORD
          value: No1Bug2Please3!
