apiVersion: v1
kind: Service
metadata:
  name: powerjob-mysql
spec:
  ports:
  - name: mysql-port
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: powerjob-mysql
  type: ClusterIP